/*
 *  this is Junit test application designed to test Permutation.java
 *  checks that permutation generated by generatePermutation is correct or not
 * */

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

import org.junit.Before;
import org.junit.Test;

public class TestPermutation {
	//References
	Permutation perm;
	String str;
	Scanner sc;
	List<String> exceptedOutput;
	
	@Before
	public void setUp() throws Exception {
		perm = new Permutation();
		sc = new Scanner(System.in);
		
		exceptedOutput = new ArrayList<String>( Arrays.asList("ABC","ACB","BAC","BCA","CBA","CAB") );
		
		sc.delimiter();
		 str = sc.next();
	}
	

	@Test
	public void test() {
		perm.generatePermutation(str, 0,str.length()-1 );
		
		assertArrayEquals(exceptedOutput.toArray(),perm.permutationOfString.toArray());
	}

}
